#!/bin/bash
echo "Run Date: ${1}"

/usr/hdp/current/spark2-client/bin/spark-submit --files "/usr/hdp/current/spark-client/conf/hive-site.xml,/usr/hdp/current/spark2-client/conf/hbase-site.xml"  --conf "spark.pyspark.python=/data/apps/python-interpreter/anaconda3.5/bin/python3"  --conf "spark.pyspark.driver.python=/data/apps/python-interpreter/anaconda3.5/bin/python3" --jars "/usr/hdp/current/hbase-client/lib/hbase-annotations-1.1.2.2.6.3.41-3-tests.jar,/usr/hdp/current/hbase-client/lib/hbase-annotations-1.1.2.2.6.3.41-3.jar,/usr/hdp/current/hbase-client/lib/hbase-client-1.1.2.2.6.3.41-3.jar,/usr/hdp/current/hbase-client/lib/hbase-common-1.1.2.2.6.3.41-3-tests.jar,/usr/hdp/current/hbase-client/lib/hbase-common-1.1.2.2.6.3.41-3.jar,/usr/hdp/current/hbase-client/lib/hbase-examples-1.1.2.2.6.3.41-3.jar,/usr/hdp/current/hbase-client/lib/hbase-hadoop-compat-1.1.2.2.6.3.41-3.jar,/usr/hdp/current/hbase-client/lib/hbase-hadoop2-compat-1.1.2.2.6.3.41-3.jar,/usr/hdp/current/hbase-client/lib/hbase-it-1.1.2.2.6.3.41-3-tests.jar,/usr/hdp/current/hbase-client/lib/hbase-it-1.1.2.2.6.3.41-3.jar,/usr/hdp/current/hbase-client/lib/hbase-prefix-tree-1.1.2.2.6.3.41-3.jar,/usr/hdp/current/hbase-client/lib/hbase-procedure-1.1.2.2.6.3.41-3.jar,/usr/hdp/current/hbase-client/lib/hbase-protocol-1.1.2.2.6.3.41-3.jar,/usr/hdp/current/hbase-client/lib/hbase-resource-bundle-1.1.2.2.6.3.41-3.jar,/usr/hdp/current/hbase-client/lib/hbase-rest-1.1.2.2.6.3.41-3.jar,/usr/hdp/current/hbase-client/lib/hbase-rsgroup-1.1.2.2.6.3.41-3-tests.jar,/usr/hdp/current/hbase-client/lib/hbase-rsgroup-1.1.2.2.6.3.41-3.jar,/usr/hdp/current/hbase-client/lib/hbase-server-1.1.2.2.6.3.41-3-tests.jar,/usr/hdp/current/hbase-client/lib/hbase-server-1.1.2.2.6.3.41-3.jar,/usr/hdp/current/hbase-client/lib/hbase-shell-1.1.2.2.6.3.41-3.jar,/usr/hdp/current/hbase-client/lib/hbase-spark-1.1.2.2.6.3.41-3.jar,/usr/hdp/current/hbase-client/lib/hbase-thrift-1.1.2.2.6.3.41-3.jar,/usr/hdp/current/hive-client/lib/hive-hbase-handler-1.2.1000.2.6.3.41-3.jar" /data/apps/0zy/scripts/operations/scripts/iperform_jobs_report.py --id iPerformCare@sprint.com,iPerformRetail@sprint.com --date "${1}"
if [ "$?" -eq 0 ]; then
        echo "inside block"
        rm /data/apps/0zy/scripts/operations/outputs/retail.html
        rm /data/apps/0zy/scripts/operations/outputs/care.html
        rm /data/apps/0zy/scripts/operations/outputs/iperform_retail_jobs.html
        rm /data/apps/0zy/scripts/operations/outputs/iperform_care_jobs.html
fi
